apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-jnfk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-dbmn-tenant/test-app-miyz/devfile-sample-python-basic-jnfk@sha256:6faa79e2c2804c6c4508959138293da57d1508b29508adbb5d1af365c2d78e69
        name: my-python
        resources: {}
status: {}
